import { readFileSync } from 'node:fs';
import { CodegenError } from './model.js';

/**
 * NAV publishes its error catalogues as Java properties files, one per
 * language, keyed by the enum constant the service reports.
 *
 * Generating a typed catalogue from them has two payoffs: a rule in this
 * library can only cite a fault code NAV actually defines, because the
 * compiler checks it against the generated union; and a locally detected
 * problem can be reported with the same wording the service would use.
 */

const LANGUAGES = ['en', 'hu', 'de'] as const;
type Language = (typeof LANGUAGES)[number];

interface Catalogue {
  /** Enum whose constants key the file, e.g. `ValidatorFaultType`. */
  enumName: string;
  /** Base file name, e.g. `validations`. */
  file: string;
  /** Name of the generated constant. */
  constName: string;
  /** Name of the generated code union. */
  typeName: string;
  doc: string;
}

const CATALOGUES: Catalogue[] = [
  {
    enumName: 'ValidatorFaultType',
    file: 'validations',
    constName: 'NAV_FAULT_MESSAGES',
    typeName: 'NavFaultCode',
    doc: `Validation faults NAV reports against an invoice.

These are the codes that appear in \`businessValidationMessages\` and
\`technicalValidationMessages\`. Many are decidable from the document alone
and are checked locally by the validation module; others depend on state only
NAV holds, such as whether an invoice number has been used before.`,
  },
  {
    enumName: 'InterfaceErrorCode',
    file: 'messages',
    constName: 'NAV_INTERFACE_MESSAGES',
    typeName: 'NavInterfaceErrorCode',
    doc: `Interface level errors NAV reports about a request as a whole.

These appear as \`result/errorCode\` in a \`GeneralErrorResponse\` — a bad
signature, an unknown technical user, a malformed request.`,
  },
];

export function emitMessages(schemasDir: string): string {
  const chunks: string[] = [
    `// Generated by @open-nav/codegen from schemas/i18n. Do not edit.
//
// Regenerate with:  pnpm codegen
// Provenance:       schemas/sources.json
`,
  ];

  for (const catalogue of CATALOGUES) {
    const byLanguage = new Map<Language, Map<string, string>>();
    for (const language of LANGUAGES) {
      byLanguage.set(
        language,
        readCatalogue(
          `${schemasDir}/i18n/${catalogue.file}_${language}_public.properties`,
          catalogue.enumName,
        ),
      );
    }

    // English is the reference set; a code missing a translation still gets an
    // entry, so a code is never dropped for want of a German sentence.
    const codes = [...(byLanguage.get('en') ?? new Map()).keys()].sort();
    if (codes.length === 0) {
      throw new CodegenError(`No ${catalogue.enumName} codes found in schemas/i18n`);
    }

    // Every language key is always present, with an empty string where NAV
    // ships no text (SCHEMA_VIOLATION). A uniform shape keeps the generated
    // constant indexable by a language variable while the keys stay a literal
    // union, which is what makes fault codes checkable at compile time.
    const entries = codes
      .map((code) => {
        const parts = LANGUAGES.map((language) => {
          const message = byLanguage.get(language)?.get(code) ?? '';
          return `${language}: ${JSON.stringify(message)}`;
        });
        return `  ${code}: { ${parts.join(', ')} },`;
      })
      .join('\n');

    chunks.push(
      `/**\n${catalogue.doc
        .split('\n')
        .map((line) => ` * ${line}`.trimEnd())
        .join(
          '\n',
        )}\n */\nexport const ${catalogue.constName} = {\n${entries}\n} as const satisfies Record<string, { en: string; hu: string; de: string }>;\n`,
      `/** Every ${catalogue.enumName} code NAV defines. */\nexport type ${catalogue.typeName} = keyof typeof ${catalogue.constName};\n`,
    );
  }

  return chunks.join('\n');
}

function readCatalogue(path: string, enumName: string): Map<string, string> {
  const prefix = `common.dto.exception.enums.${enumName}.`;
  const entries = new Map<string, string>();

  for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    if (line.trim() === '' || line.trimStart().startsWith('#')) continue;
    const separator = line.indexOf('=');
    if (separator === -1) throw new CodegenError(`Malformed properties line in ${path}: ${line}`);
    const key = line.slice(0, separator).trim();
    if (!key.startsWith(prefix)) continue;
    const code = key.slice(prefix.length);
    if (!/^[A-Z][A-Z0-9_]*$/.test(code)) {
      throw new CodegenError(`Unexpected code ${code} in ${path}`);
    }
    const message = line.slice(separator + 1).trim();
    // SCHEMA_VIOLATION has no message text upstream; keep the code, drop the text.
    if (message !== '') entries.set(code, message);
    else if (!entries.has(code)) entries.set(code, '');
  }

  return entries;
}
