import {
  CodegenError,
  type ComplexTypeDef,
  type Doc,
  type Facets,
  type PrimitiveKind,
  type SchemaModel,
  type SimpleTypeDef,
  type TypeDef,
} from './model.js';

/**
 * How each XSD primitive is represented in TypeScript.
 *
 * `decimal` deliberately becomes `string`. NAV's `MonetaryType` allows 18
 * digits, so scaling to minor units overflows `Number.MAX_SAFE_INTEGER` at
 * the top of the range, and binary floating point cannot represent a rate
 * like `0.27` exactly. Since NAV rejects a batch whose lines fail to
 * reconcile with its summary by a single fillér, the wire model keeps
 * decimals as exact text and leaves arithmetic to a decimal type.
 */
const TS_PRIMITIVES: Record<PrimitiveKind, string> = {
  string: 'string',
  decimal: 'string',
  integer: 'number',
  boolean: 'boolean',
  date: 'string',
  dateTime: 'string',
  base64Binary: 'string',
};

const XS_PRIMITIVE_KINDS: Record<string, PrimitiveKind> = {
  'xs:string': 'string',
  'xs:decimal': 'decimal',
  'xs:int': 'integer',
  'xs:integer': 'integer',
  'xs:long': 'integer',
  'xs:nonNegativeInteger': 'integer',
  'xs:positiveInteger': 'integer',
  'xs:boolean': 'boolean',
  'xs:date': 'date',
  'xs:dateTime': 'dateTime',
  'xs:base64Binary': 'base64Binary',
};

const HEADER = `// Generated by @open-nav/codegen from the XSDs in schemas/. Do not edit.
//
// Regenerate with:  pnpm codegen
// Provenance:       schemas/sources.json
`;

/** Assign a unique TypeScript name to every type key. */
function nameTypes(model: SchemaModel): Map<string, string> {
  const counts = new Map<string, number>();
  for (const def of model.types.values()) {
    counts.set(def.name, (counts.get(def.name) ?? 0) + 1);
  }
  const names = new Map<string, string>();
  for (const [key, def] of model.types) {
    const collides = (counts.get(def.name) ?? 0) > 1;
    const prefix = def.ns.charAt(0).toUpperCase() + def.ns.slice(1);
    names.set(key, collides ? `${prefix}${def.name}` : def.name);
  }
  return names;
}

function jsdoc(doc: Doc, indent: string, extra: string[] = []): string {
  const lines: string[] = [];
  if (doc.en) lines.push(...wrap(doc.en, 76));
  if (doc.hu) {
    if (lines.length > 0) lines.push('');
    lines.push(...wrap(doc.hu, 76));
  }
  lines.push(...extra);
  if (lines.length === 0) return '';
  const body = lines.map((line) => `${indent} *${line ? ` ${line}` : ''}`).join('\n');
  return `${indent}/**\n${body}\n${indent} */\n`;
}

function wrap(text: string, width: number): string[] {
  // Comment terminators inside NAV's documentation would close the JSDoc.
  const clean = text.replace(/\*\//g, '*​/').replace(/\s+/g, ' ').trim();
  const out: string[] = [];
  let line = '';
  for (const word of clean.split(' ')) {
    if (line.length > 0 && line.length + word.length + 1 > width) {
      out.push(line);
      line = word;
    } else {
      line = line.length > 0 ? `${line} ${word}` : word;
    }
  }
  if (line) out.push(line);
  return out;
}

function tsTypeOf(typeKey: string, model: SchemaModel, names: Map<string, string>): string {
  const primitive = XS_PRIMITIVE_KINDS[typeKey];
  if (primitive) return TS_PRIMITIVES[primitive];
  const name = names.get(typeKey);
  if (!name) throw new CodegenError(`No TypeScript name for type ${typeKey}`);
  const def = model.types.get(typeKey);
  if (def?.kind === 'simple' && !def.facets.enumValues) {
    // Non-enum simple types are transparent aliases; inline the primitive so
    // consumers are not forced through a meaningless indirection.
    return TS_PRIMITIVES[def.facets.primitive];
  }
  return name;
}

/** Emit the TypeScript type declarations. */
export function emitTypes(model: SchemaModel, names: Map<string, string>): string {
  const chunks: string[] = [
    HEADER,
    `
/**
 * TypeScript shape of the NAV Online Számla 3.0 documents.
 *
 * These are wire types: field names, order and nullability come straight from
 * the schema, and every decimal is an exact decimal string rather than a
 * JavaScript number. See TS_PRIMITIVES in the generator for why.
 */
`,
  ];

  const sorted = [...model.types.values()].sort((a, b) => a.name.localeCompare(b.name));

  for (const def of sorted) {
    if (def.kind === 'simple') {
      if (!def.facets.enumValues) continue; // transparent alias, inlined at use sites
      chunks.push(emitEnum(def, names));
    } else {
      chunks.push(emitInterface(def, model, names));
    }
  }

  chunks.push(emitRootMap(model, names));
  return chunks.join('\n');
}

function emitEnum(def: SimpleTypeDef, names: Map<string, string>): string {
  const name = names.get(def.key)!;
  const values = def.facets.enumValues!.map((value) => `  | '${value}'`).join('\n');
  return `${jsdoc(def.doc, '')}export type ${name} =\n${values};\n`;
}

function emitInterface(
  def: ComplexTypeDef,
  model: SchemaModel,
  names: Map<string, string>,
): string {
  const name = names.get(def.key)!;
  const extra: string[] = [];
  for (const group of def.choiceGroups) {
    extra.push(
      '',
      `@remarks ${group.required ? 'Exactly one' : 'At most one'} of ` +
        `${group.members.map((member) => `\`${member}\``).join(', ')} may be set.`,
    );
  }

  if (def.content === 'simple') {
    const contentType = tsTypeOf(def.contentTypeKey!, model, names);
    const attributes = def.attributes
      .map((attribute) => {
        const type = tsTypeOf(attribute.typeKey, model, names);
        return `${jsdoc(attribute.doc, '  ')}  ${attribute.name}${attribute.required ? '' : '?'}: ${type};`;
      })
      .join('\n');
    return `${jsdoc(def.doc, '', extra)}export interface ${name} {\n  /** Text content of the element. */\n  value: ${contentType};\n${attributes}\n}\n`;
  }

  const fields = def.fields
    .map((field) => {
      const base = tsTypeOf(field.typeKey, model, names);
      const repeated = field.maxOccurs === null || field.maxOccurs > 1;
      const type = repeated ? `${base}[]` : base;
      const optional = field.minOccurs === 0 ? '?' : '';
      const bounds =
        repeated && field.maxOccurs !== null
          ? [``, `@remarks At most ${field.maxOccurs} entries.`]
          : [];
      return `${jsdoc(field.doc, '  ', bounds)}  ${field.name}${optional}: ${type};`;
    })
    .join('\n');

  const body = def.fields.length > 0 ? `\n${fields}\n` : '\n';
  return `${jsdoc(def.doc, '', extra)}export interface ${name} {${body}}\n`;
}

function emitRootMap(model: SchemaModel, names: Map<string, string>): string {
  const entries = model.roots
    .map((root) => {
      const type = names.get(root.typeKey);
      if (!type) throw new CodegenError(`Root ${root.name} has no named type`);
      return `${jsdoc(root.doc, '  ')}  ${root.name}: ${type};`;
    })
    .join('\n');
  return `/**\n * Every globally declared document root, mapped to its TypeScript type.\n */\nexport interface RootDocuments {\n${entries}\n}\n`;
}

/** Emit the runtime descriptors that drive serialisation, parsing and validation. */
export function emitSchema(model: SchemaModel, names: Map<string, string>): string {
  const types = [...model.types.values()]
    .filter((def): def is ComplexTypeDef | SimpleTypeDef => true)
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((def) => `  ${JSON.stringify(def.key)}: ${descriptorLiteral(def, names)},`)
    .join('\n');

  const roots = model.roots
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(
      (root) =>
        `  ${JSON.stringify(root.name)}: { name: ${JSON.stringify(root.name)}, ns: '${root.ns}', type: ${JSON.stringify(root.typeKey)} },`,
    )
    .join('\n');

  return `${HEADER}
import type { Descriptor, RootDescriptor } from '../xml/descriptor.js';

/**
 * Every type in the Online Számla schemas, keyed by \`namespace:typeName\`.
 *
 * Element order inside \`fields\` is schema order, which is also the order NAV
 * requires on the wire. \`ns\` on each field is the namespace that declares
 * it, not its parent's: that is why a \`supplierTaxNumber\` in the data
 * namespace carries \`taxpayerId\` children in the base namespace.
 */
export const TYPES: Record<string, Descriptor> = {
${types}
};

/** Document roots, keyed by element name. */
export const ROOTS: Record<string, RootDescriptor> = {
${roots}
};
`;
}

function descriptorLiteral(def: TypeDef, names: Map<string, string>): string {
  if (def.kind === 'simple') {
    const facets = facetLiteral(def.facets);
    return `{ kind: 'simple', name: ${JSON.stringify(def.name)}, ns: '${def.ns}', tsName: ${JSON.stringify(names.get(def.key))}${facets} }`;
  }

  const parts: string[] = [
    `kind: 'complex'`,
    `name: ${JSON.stringify(def.name)}`,
    `ns: '${def.ns}'`,
    `tsName: ${JSON.stringify(names.get(def.key))}`,
    `content: '${def.content}'`,
  ];

  if (def.content === 'simple') {
    parts.push(`contentType: ${JSON.stringify(def.contentTypeKey)}`);
  }

  const fields = def.fields
    .map((field) => {
      const bits = [
        `name: ${JSON.stringify(field.name)}`,
        `ns: '${field.ns}'`,
        `type: ${JSON.stringify(field.typeKey)}`,
      ];
      if (field.minOccurs === 0) bits.push('optional: true');
      if (field.maxOccurs === null) bits.push('repeated: true');
      else if (field.maxOccurs > 1) bits.push(`repeated: true, maxOccurs: ${field.maxOccurs}`);
      return `{ ${bits.join(', ')} }`;
    })
    .join(', ');
  parts.push(`fields: [${fields}]`);

  if (def.choiceGroups.length > 0) {
    const groups = def.choiceGroups
      .map((group) => `{ members: ${JSON.stringify(group.members)}, required: ${group.required} }`)
      .join(', ');
    parts.push(`choiceGroups: [${groups}]`);
  }

  if (def.attributes.length > 0) {
    const attributes = def.attributes
      .map(
        (attribute) =>
          `{ name: ${JSON.stringify(attribute.name)}, type: ${JSON.stringify(attribute.typeKey)}, required: ${attribute.required} }`,
      )
      .join(', ');
    parts.push(`attributes: [${attributes}]`);
  }

  return `{ ${parts.join(', ')} }`;
}

function facetLiteral(facets: Facets): string {
  const parts: string[] = [`, primitive: '${facets.primitive}'`];
  if (facets.enumValues) parts.push(`, enumValues: ${JSON.stringify(facets.enumValues)}`);
  if (facets.pattern !== undefined) parts.push(`, pattern: ${JSON.stringify(facets.pattern)}`);
  for (const key of [
    'length',
    'minLength',
    'maxLength',
    'totalDigits',
    'fractionDigits',
  ] as const) {
    const value = facets[key];
    if (value !== undefined) parts.push(`, ${key}: ${value}`);
  }
  for (const key of ['minInclusive', 'maxInclusive', 'minExclusive', 'maxExclusive'] as const) {
    const value = facets[key];
    if (value !== undefined) parts.push(`, ${key}: ${JSON.stringify(value)}`);
  }
  return parts.join('');
}

export { nameTypes };
