import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { emitSchema, emitTypes, nameTypes } from './emit.js';
import { emitMessages } from './emit-messages.js';
import { parseSchemas } from './parse.js';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..', '..');

/**
 * Load order does not matter — references are resolved across all files once
 * everything is parsed — but keeping it dependency-first makes failures
 * easier to read.
 */
const SCHEMA_FILES = [
  'schemas/NTCA/1.0/common.xsd',
  'schemas/OSA/3.0/invoiceBase.xsd',
  'schemas/OSA/3.0/invoiceData.xsd',
  'schemas/OSA/3.0/invoiceAnnulment.xsd',
  'schemas/OSA/3.0/invoiceApi.xsd',
  'schemas/OSA/3.0/serviceMetrics.xsd',
];

const OUT_DIR = 'packages/core/src/generated';

function main(): void {
  const model = parseSchemas(SCHEMA_FILES.map((file) => join(repoRoot, file)));
  const names = nameTypes(model);

  const outDir = join(repoRoot, OUT_DIR);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'types.ts'), emitTypes(model, names), 'utf8');
  writeFileSync(join(outDir, 'schema.ts'), emitSchema(model, names), 'utf8');
  writeFileSync(join(outDir, 'fault-codes.ts'), emitMessages(join(repoRoot, 'schemas')), 'utf8');
  writeFileSync(
    join(outDir, 'index.ts'),
    `// Generated by @open-nav/codegen. Do not edit.\nexport * from './types.js';\nexport * from './schema.js';\nexport * from './fault-codes.js';\n`,
    'utf8',
  );

  const complex = [...model.types.values()].filter((def) => def.kind === 'complex').length;
  const simple = model.types.size - complex;
  console.log(
    `Generated ${model.types.size} types (${complex} complex, ${simple} simple), ` +
      `${model.roots.length} document roots and the NAV error catalogues into ${OUT_DIR}`,
  );
}

main();
