import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { emitSchema, emitTypes, nameTypes } from './emit.js';
import { emitMessages } from './emit-messages.js';
import { parseSchemas } from './parse.js';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..', '..');

/**
 * One generated package per NAV system. Load order within a target does not
 * matter — references are resolved across all its files once parsed — but
 * keeping it dependency-first makes failures easier to read.
 *
 * `messages: true` also emits the NAV fault-code catalogues (from the vendored
 * i18n `.properties` files, which only exist for Online Számla).
 */
interface Target {
  label: string;
  schemaFiles: string[];
  outDir: string;
  messages: boolean;
}

const TARGETS: Target[] = [
  {
    label: 'Online Számla (OSA 3.0)',
    schemaFiles: [
      'schemas/NTCA/1.0/common.xsd',
      'schemas/OSA/3.0/invoiceBase.xsd',
      'schemas/OSA/3.0/invoiceData.xsd',
      'schemas/OSA/3.0/invoiceAnnulment.xsd',
      'schemas/OSA/3.0/invoiceApi.xsd',
      'schemas/OSA/3.0/serviceMetrics.xsd',
    ],
    outDir: 'packages/core/src/generated',
    messages: true,
  },
  {
    label: 'eÁFA / eVAT (EAR 2.0)',
    schemaFiles: [
      'schemas/NTCA/1.0/common.xsd',
      'schemas/EAR/2.0/earBase.xsd',
      'schemas/EAR/2.0/earData.xsd',
      'schemas/EAR/2.0/earAPI.xsd',
    ],
    outDir: 'packages/evat/src/generated',
    messages: false,
  },
  {
    label: 'eNyugta / eReceipt (ERECEIPT 1.1)',
    // documentData embeds the OSA invoice *data* (invoiceData), but not the OSA
    // online-invoice API (invoiceApi), so that is deliberately left out.
    schemaFiles: [
      'schemas/ERECEIPT/1.0/common.xsd',
      'schemas/ERECEIPT/1.0/invoiceBase.xsd',
      'schemas/ERECEIPT/1.0/invoiceData.xsd',
      'schemas/ERECEIPT/1.1/eReceiptBase.xsd',
      'schemas/ERECEIPT/1.1/communicationData.xsd',
      'schemas/ERECEIPT/1.1/documentData.xsd',
      'schemas/ERECEIPT/1.1/documentMessage.xsd',
      'schemas/ERECEIPT/1.1/reportMessage.xsd',
      'schemas/ERECEIPT/1.1/eReceiptApi.xsd',
    ],
    outDir: 'packages/receipt/src/generated',
    messages: false,
  },
];

function generate(target: Target): void {
  const model = parseSchemas(target.schemaFiles.map((file) => join(repoRoot, file)));
  const names = nameTypes(model);

  const outDir = join(repoRoot, target.outDir);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'types.ts'), emitTypes(model, names), 'utf8');
  writeFileSync(join(outDir, 'schema.ts'), emitSchema(model, names), 'utf8');

  const exports = ["export * from './types.js';", "export * from './schema.js';"];
  if (target.messages) {
    writeFileSync(join(outDir, 'fault-codes.ts'), emitMessages(join(repoRoot, 'schemas')), 'utf8');
    exports.push("export * from './fault-codes.js';");
  }
  writeFileSync(
    join(outDir, 'index.ts'),
    `// Generated by @open-nav/codegen. Do not edit.\n${exports.join('\n')}\n`,
    'utf8',
  );

  const complex = [...model.types.values()].filter((def) => def.kind === 'complex').length;
  const simple = model.types.size - complex;
  console.log(
    `${target.label}: ${model.types.size} types (${complex} complex, ${simple} simple), ` +
      `${model.roots.length} document roots${target.messages ? ' + NAV error catalogues' : ''} -> ${target.outDir}`,
  );
}

function main(): void {
  for (const target of TARGETS) generate(target);
}

main();
