#!/usr/bin/env python3
"""Generate the typed eVAT standard tax-code catalogue.

Reads the vendored NAV catalogue spreadsheet and emits a typed TypeScript
module (`packages/evat/src/generated/tax-codes.ts`) with one entry per standard
tax code: the code, its "speaking" mnemonic, description, and the VAT-return
rows it maps to. The raw .xlsx is vendored by scripts/vendor_schemas.py; this
turns it into reviewable, diffable data.

    python3 scripts/generate_tax_codes.py            # regenerate
    python3 scripts/generate_tax_codes.py --check    # fail if stale

Requires openpyxl (pip install openpyxl).
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

import openpyxl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(
    ROOT, 'schemas/EAR/tax-code-catalog/TAX_CODE_CATALOG_20260904_extended.xlsx'
)
OUT = os.path.join(ROOT, 'packages/evat/src/generated/tax-codes.ts')
# The catalogue's own version, from the published file name.
CATALOG_VERSION = '2026-09-04'

# Spreadsheet column index -> emitted field name. Column 0 (Sorszám) and 2/3
# (computed value, check flag) are omitted.
FIELDS: list[tuple[int, str]] = [
    (1, 'code'),
    (4, 'speakingCode'),
    (5, 'description'),
    (6, 'payableMainRow1'),
    (7, 'payableMainRow2'),
    (8, 'payableDetailRow1'),
    (9, 'payableDetailRow2'),
    (10, 'payableDetailRow3'),
    (11, 'deductibleMainRow'),
    (12, 'deductibleMainRowSubcase'),
    (13, 'deductibleHighlightRow1'),
    (14, 'deductibleHighlightRow2'),
    (15, 'deductibleHighlightRow3'),
    (16, 'detailHighlightRow1'),
    (17, 'detailHighlightRow2'),
    (18, 'page'),
    (19, 'supplementaryType'),
    (20, 'supplementaryValue'),
]
# Fields present on every meaningful row.
REQUIRED = {'code', 'speakingCode', 'description'}


def cell(value: object) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def read_rows() -> list[dict[str, str]]:
    workbook = openpyxl.load_workbook(CATALOG, read_only=True, data_only=True)
    sheet = workbook.active
    rows: list[dict[str, str]] = []
    for index, row in enumerate(sheet.iter_rows(values_only=True)):
        if index == 0:
            continue  # header
        entry: dict[str, str] = {}
        for column, name in FIELDS:
            text = cell(row[column]) if column < len(row) else None
            if text is not None:
                entry[name] = text
        if 'code' in entry:
            rows.append(entry)
    return rows


def escape(text: str) -> str:
    # Collapse embedded newlines/tabs so each value stays a single-line literal.
    collapsed = ' '.join(text.split())
    return collapsed.replace('\\', '\\\\').replace("'", "\\'")


def render(rows: list[dict[str, str]]) -> str:
    lines = [
        '// Generated by scripts/generate_tax_codes.py. Do not edit.',
        '// Source: schemas/EAR/tax-code-catalog (vendored from nav-gov-hu/eVAT).',
        '',
        '/**',
        ' * A standard eVAT tax code: the code that classifies a VAT ledger line, and',
        ' * the VAT-return rows it maps to. Optional fields are absent when the',
        ' * catalogue leaves them blank.',
        ' */',
        'export interface TaxCode {',
    ]
    docs = {
        'code': 'Standard tax code, e.g. `MP01 DP37`.',
        'speakingCode': 'Human-readable ("beszédes") code, e.g. `F01 37`.',
        'description': 'Hungarian description of the code.',
        'payableMainRow1': 'Payable main row 1 (MP).',
        'payableMainRow2': 'Payable main row 2 (MP).',
        'payableDetailRow1': 'Payable detail row 1 (DP).',
        'payableDetailRow2': 'Payable detail row 2 (DP).',
        'payableDetailRow3': 'Payable detail row 3 (DP).',
        'deductibleMainRow': 'Deductible main row (MD).',
        'deductibleMainRowSubcase': 'Deductible main-row subcase (MD).',
        'deductibleHighlightRow1': 'Deductible highlight row 1 (DD).',
        'deductibleHighlightRow2': 'Deductible highlight row 2 (DD).',
        'deductibleHighlightRow3': 'Deductible highlight row 3 (DD).',
        'detailHighlightRow1': 'Detail highlight row (DH).',
        'detailHighlightRow2': 'Detail highlight row 2 (DH).',
        'page': 'Return page (PG).',
        'supplementaryType': 'Supplementary type (V).',
        'supplementaryValue': 'Supplementary type value.',
    }
    for _, name in FIELDS:
        optional = '' if name in REQUIRED else '?'
        lines.append(f'  /** {docs[name]} */')
        lines.append(f'  {name}{optional}: string;')
    lines.append('}')
    lines.append('')
    lines.append(f"/** Version of the vendored NAV tax-code catalogue. */")
    lines.append(f"export const TAX_CODE_CATALOG_VERSION = '{CATALOG_VERSION}';")
    lines.append('')
    lines.append('/** Every standard eVAT tax code, in catalogue order. */')
    lines.append('export const TAX_CODES: readonly TaxCode[] = [')
    for entry in rows:
        parts = [f"{name}: '{escape(entry[name])}'" for _, name in FIELDS if name in entry]
        lines.append('  { ' + ', '.join(parts) + ' },')
    lines.append('];')
    lines.append('')
    lines.append('/** Standard tax codes indexed by `code`. */')
    lines.append(
        'export const TAX_CODES_BY_CODE: ReadonlyMap<string, TaxCode> = new Map('
    )
    lines.append('  TAX_CODES.map((entry) => [entry.code, entry]),')
    lines.append(');')
    lines.append('')
    lines.append('/** Look up a standard tax code by its exact code string. */')
    lines.append('export function taxCode(code: string): TaxCode | undefined {')
    lines.append('  return TAX_CODES_BY_CODE.get(code);')
    lines.append('}')
    lines.append('')
    return '\n'.join(lines)


def prettier(source: str) -> str:
    """Format the generated TypeScript with the repo's Prettier.

    The committed file is Prettier-formatted (as all source is), so the check
    must compare against the same — otherwise a formatting-only difference reads
    as stale. Requires Node/Prettier on PATH (the repo's dev/CI environment).
    """
    result = subprocess.run(
        ['npx', 'prettier', '--stdin-filepath', OUT],
        input=source, capture_output=True, text=True, cwd=ROOT,
    )
    if result.returncode != 0:
        raise SystemExit(f'prettier failed: {result.stderr.strip()}')
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()

    generated = prettier(render(read_rows()))
    if args.check:
        current = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if current.strip() != generated.strip():
            print('tax-codes.ts is out of date. Run: python3 scripts/generate_tax_codes.py',
                  file=sys.stderr)
            return 1
        print('tax-codes.ts matches the catalogue.')
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as handle:
        handle.write(generated)
    print(f'Generated {OUT} from the {CATALOG_VERSION} catalogue.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
